### ISSUE TITLE
proxy

### ISSUE THREAD

**Issue by rich-money** [mliu027/Vultr-Proxy-Maker#2]
so i need a seperate script to make proxies in startup script section of vultr or i use your py script im confused. I thought start up script was for public rsa key. Can you please further explain thank you.

**Comment by mliu027** [comment]
You need a start up script in vultr. That start up script is used to make the server into a proxy. The py script is used to make multiple proxies at once. 

What are you using the proxies for?

**Comment by rich-money** [comment]
Im using for a web scrapper.

**Comment by rich-money** [comment]
Any idea where i can get the appropriate startup script?

**Comment by mliu027** [comment]
Google
